apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-rrmyhdwv
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-rrmyhdwv:9631036b429501d89e73a0ce4238e9dcc1bc0e68@sha256:327a084d34c23d5d306ace8967d4bec820ddeec06e56c06d51bea126563e0ceb
        name: container-image  
